### ISSUE TITLE
Create an uninstall file

### ISSUE THREAD

**Issue by giacomo-secchi** [giacomo-secchi/write-poetry#15]
Create `uninstall.php` file in order to remove plugin database field used by this plugin
Problem to fix and complete the tests:

- [x] Check that the uninstall process removes all fields starting with `writepoetry `in the `wp_options `database table
Related error:
```
[24-Jan-2024 11:36:59 UTC] PHP Fatal error:  Uncaught Error: Class "WritePoetry\Api\PluginConfig" not found in C:\Users\giacomo.secchi\Local Sites\test\app\public\wp-content\plugins\write-poetry\uninstall.php:12
Stack trace:
#0 C:\Users\username\Local Sites\test\app\public\wp-admin\includes\plugin.php(1245): include_once()
#1 C:\Users\username\Local Sites\test\app\public\wp-admin\includes\plugin.php(960): uninstall_plugin('write-poetry')
#2 C:\Users\username\Local Sites\test\app\public\wp-admin\includes\ajax-actions.php(4748): delete_plugins(Array)
#3 C:\Users\username\Local Sites\test\app\public\wp-includes\class-wp-hook.php(324): wp_ajax_delete_plugin('')
#4 C:\Users\username\Local Sites\test\app\public\wp-includes\class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#5 C:\Users\username\Local Sites\test\app\public\wp-includes\plugin.php(517): WP_Hook->do_action(Array)
#6 C:\Users\username\Local Sites\test\app\public\wp-admin\admin-ajax.php(188): do_action('wp_ajax_delete-...')
#7 {main}
  thrown in C:\Users\username\Local Sites\test\app\public\wp-content\plugins\write-poetry\uninstall.php on line 12
```

- [x] Ensure that no errors occur when enabling or disabling the plugin multiple times
Related Error:
```
[24-Jan-2024 11:04:05 UTC] PHP Fatal error:  Uncaught Error: Class "WritePoetry\Base\Activate" not found in C:\Users\username\Local Sites\test\app\public\wp-content\plugins\write-poetry\write-poetry.php:40
Stack trace:
#0 C:\Users\username\Local Sites\test\app\public\wp-includes\class-wp-hook.php(324): {closure}(false)
#1 C:\Users\username\Local Sites\test\app\public\wp-includes\class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#2 C:\Users\username\Local Sites\test\app\public\wp-includes\plugin.php(517): WP_Hook->do_action(Array)
#3 C:\Users\username\Local Sites\test\app\public\wp-admin\includes\plugin.php(693): do_action('activate_write...', false)
#4 C:\Users\username\Local Sites\test\app\public\wp-admin\plugins.php(58): activate_plugin('write-poetry', 'http://test.loc...', false)
#5 {main}
  thrown in C:\Users\username\Local Sites\test\app\public\wp-content\plugins\write-poetry\write-poetry.php on line 40
```

**Comment by giacomo-secchi** [comment]
When I try to uninstall the plugin, when i click on **Delete** button this error message appears:
Deletion failed: There has been a critical error on this website.Learn more about troubleshooting WordPress.

**Comment by anumit-web** [comment]
I will do that. I will try to see why deleting is not working.

**Comment by giacomo-secchi** [comment]
Errors are fixed.

**Comment by anumit-web** [comment]
That's great Boss.
You are expert at coding.
